import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import { Rectangle } from "../components/Rectangle";
import { Stage } from "@inlet/react-pixi";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Stage>
            <Rectangle
              x={100}
              y={100}
              width={100}
              height={100}
              color={0xff0000}
            />
          </Stage>
        </div>
      </main>
    </>
  );
};

export default Home;
